version: '3.9'

services:

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  web:
    build: ./web
    container_name: "eureka-web"
    volumes:
      - ./web/:/web/
    env_file:
      - ./.env.dev
    ports:
      - "5000:5000"
    depends_on:
      - db

  machine:
    build: ./machine
    container_name: "eureka-machine"
    volumes:
      - ./machine/:/machine/
    env_file:
      - ./.env.dev
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  postgres_data:
