version: '3.9'

services:

  web:
    build: ./web
    container_name: "eureka-web"
    command: python app.py
    volumes:
      - ./web/:/web/
    env_file:
      - ./.env.dev
    ports:
      - "5000:5000"

  machine:
    build: ./machine
    container_name: "eureka-machine"
    command: python app.py
    volumes:
      - ./machine/:/machine/
    env_file:
      - ./.env.dev
    ports:
      - "5001:5001"

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
