"""remove number

Revision ID: 656ea57fbbfb
Revises: b2bd02311f55
Create Date: 2024-01-10 19:22:11.991780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656ea57fbbfb'
down_revision = 'b2bd02311f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
