"""Order Status added

Revision ID: b2bd02311f55
Revises: 2398d44da1b5
Create Date: 2024-01-10 18:19:44.525375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bd02311f55'
down_revision = '2398d44da1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
